// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"fmt"
	"github.com/facebookincubator/symphony/pkg/log"
	"github.com/facebookincubator/symphony/pkg/server"
	viewer2 "github.com/facebookincubator/symphony/pkg/viewer"
	"github.com/net-auto/resourceManager/ent"
	"github.com/net-auto/resourceManager/graph/graphhttp"
	"github.com/net-auto/resourceManager/psql"
	"github.com/net-auto/resourceManager/viewer"
	"gocloud.dev/server/health"
)

import (
	_ "github.com/net-auto/resourceManager/ent/runtime"
)

// Injectors from wire.go:

func newApplication(ctx context.Context, flags *cliFlags) (*application, func(), error) {
	config := flags.LogConfig
	logger, cleanup, err := log.ProvideLogger(config)
	if err != nil {
		return nil, nil, err
	}
	psqlConfig := flags.PsqlConfig
	viewerConfig := flags.TenancyConfig
	psqlTenancy, err := newPsqlTenancy(psqlConfig, viewerConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tenancy, err := newTenancy(psqlTenancy)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	telemetryConfig := &flags.TelemetryConfig
	v := newHealthChecks(psqlTenancy)
	graphhttpConfig := graphhttp.Config{
		Tenancy:      tenancy,
		Logger:       logger,
		Telemetry:    telemetryConfig,
		HealthChecks: v,
	}
	server, cleanup2, err := graphhttp.NewServer(graphhttpConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mainApplication := newApp(logger, server, flags)
	return mainApplication, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func newApp(logger log.Logger, httpServer *server.Server, flags *cliFlags) *application {
	var app application
	app.Logger = logger.Background()
	app.http.Server = httpServer
	app.http.addr = flags.HTTPAddr
	return &app
}

func newTenancy(tenancy *viewer.PsqlTenancy) (viewer.Tenancy, error) {
	initFunc := func(*ent.Client) {

	}
	return viewer.NewCacheTenancy(tenancy, initFunc), nil
}

func newHealthChecks(tenancy *viewer.PsqlTenancy) []health.Checker {
	return []health.Checker{tenancy}
}

func newPsqlTenancy(config psql.Config, tenancyConfig viewer2.Config, logger log.Logger) (*viewer.PsqlTenancy, error) {
	tenancy, err := viewer.NewPsqlTenancy(config.String(), tenancyConfig.TenantMaxConn)
	if err != nil {
		return nil, fmt.Errorf("creating psql tenancy: %w", err)
	}
	tenancy.SetLogger(logger)
	psql.SetLogger(&config, logger)
	return tenancy, nil
}
