version: "3.8"

services:

  postgresql:
    container_name: postgresql
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - LC_COLLATE=en_US.UTF-8
      - LC_CTYPE=en_US.UTF-8
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db-name -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  resource-manager:
    container_name: resource-manager
    image: frinx/resource-manager
    user: root
    environment:
      - RM_DB_CONNECTION_STRING=postgres://postgres:postgres@postgresql:5432/postgres?sslmode=disable
      - RM_API_PORT=8884
      - RM_ADMIN_ROLES=OWNER
      - RM_ADMIN_GROUPS=NETWORK-ADMIN
      - RM_LOG_PATH=/var/log/rm.log
      - RM_LOG_LEVEL=info
      - WASMER_MAX_TIMEOUT_MILLIS=10000
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - 8884:8884
      - 2345:2345
