// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/net-auto/resourceManager/ent/poolproperties"
	"github.com/net-auto/resourceManager/ent/predicate"
)

// PoolPropertiesDelete is the builder for deleting a PoolProperties entity.
type PoolPropertiesDelete struct {
	config
	hooks    []Hook
	mutation *PoolPropertiesMutation
}

// Where adds a new predicate to the delete builder.
func (ppd *PoolPropertiesDelete) Where(ps ...predicate.PoolProperties) *PoolPropertiesDelete {
	ppd.mutation.predicates = append(ppd.mutation.predicates, ps...)
	return ppd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ppd *PoolPropertiesDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ppd.hooks) == 0 {
		affected, err = ppd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PoolPropertiesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ppd.mutation = mutation
			affected, err = ppd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ppd.hooks) - 1; i >= 0; i-- {
			mut = ppd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ppd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppd *PoolPropertiesDelete) ExecX(ctx context.Context) int {
	n, err := ppd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ppd *PoolPropertiesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: poolproperties.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: poolproperties.FieldID,
			},
		},
	}
	if ps := ppd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ppd.driver, _spec)
}

// PoolPropertiesDeleteOne is the builder for deleting a single PoolProperties entity.
type PoolPropertiesDeleteOne struct {
	ppd *PoolPropertiesDelete
}

// Exec executes the deletion query.
func (ppdo *PoolPropertiesDeleteOne) Exec(ctx context.Context) error {
	n, err := ppdo.ppd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{poolproperties.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ppdo *PoolPropertiesDeleteOne) ExecX(ctx context.Context) {
	ppdo.ppd.ExecX(ctx)
}
