// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/net-auto/resourceManager/ent/propertytype"
)

// PropertyType is the model entity for the PropertyType schema.
type PropertyType struct {
	config `gqlgen:"-" json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type propertytype.Type `json:"type,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID string `json:"external_id,omitempty"`
	// Index holds the value of the "index" field.
	Index int `json:"index,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// IntVal holds the value of the "int_val" field.
	IntVal *int `json:"intValue" gqlgen:"intValue"`
	// BoolVal holds the value of the "bool_val" field.
	BoolVal *bool `json:"booleanValue" gqlgen:"booleanValue"`
	// FloatVal holds the value of the "float_val" field.
	FloatVal *float64 `json:"floatValue" gqlgen:"floatValue"`
	// LatitudeVal holds the value of the "latitude_val" field.
	LatitudeVal *float64 `json:"latitudeValue" gqlgen:"latitudeValue"`
	// LongitudeVal holds the value of the "longitude_val" field.
	LongitudeVal *float64 `json:"longitudeValue" gqlgen:"longitudeValue"`
	// StringVal holds the value of the "string_val" field.
	StringVal *string `json:"stringValue" gqlgen:"stringValue"`
	// RangeFromVal holds the value of the "range_from_val" field.
	RangeFromVal *float64 `json:"rangeFromValue" gqlgen:"rangeFromValue"`
	// RangeToVal holds the value of the "range_to_val" field.
	RangeToVal *float64 `json:"rangeToValue" gqlgen:"rangeToValue"`
	// IsInstanceProperty holds the value of the "is_instance_property" field.
	IsInstanceProperty bool `json:"is_instance_property,omitempty" gqlgen:"isInstanceProperty"`
	// Editable holds the value of the "editable" field.
	Editable bool `json:"editable,omitempty" gqlgen:"isEditable"`
	// Mandatory holds the value of the "mandatory" field.
	Mandatory bool `json:"mandatory,omitempty" gqlgen:"isMandatory"`
	// Deleted holds the value of the "deleted" field.
	Deleted bool `json:"deleted,omitempty" gqlgen:"isDeleted"`
	// NodeType holds the value of the "nodeType" field.
	NodeType string `json:"nodeType,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PropertyTypeQuery when eager-loading is set.
	Edges                        PropertyTypeEdges `json:"edges"`
	resource_type_property_types *int
}

// PropertyTypeEdges holds the relations/edges for other nodes in the graph.
type PropertyTypeEdges struct {
	// Properties holds the value of the properties edge.
	Properties []*Property
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PropertiesOrErr returns the Properties value or an error if the edge
// was not loaded in eager-loading.
func (e PropertyTypeEdges) PropertiesOrErr() ([]*Property, error) {
	if e.loadedTypes[0] {
		return e.Properties, nil
	}
	return nil, &NotLoadedError{edge: "properties"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PropertyType) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},   // id
		&sql.NullString{},  // type
		&sql.NullString{},  // name
		&sql.NullString{},  // external_id
		&sql.NullInt64{},   // index
		&sql.NullString{},  // category
		&sql.NullInt64{},   // int_val
		&sql.NullBool{},    // bool_val
		&sql.NullFloat64{}, // float_val
		&sql.NullFloat64{}, // latitude_val
		&sql.NullFloat64{}, // longitude_val
		&sql.NullString{},  // string_val
		&sql.NullFloat64{}, // range_from_val
		&sql.NullFloat64{}, // range_to_val
		&sql.NullBool{},    // is_instance_property
		&sql.NullBool{},    // editable
		&sql.NullBool{},    // mandatory
		&sql.NullBool{},    // deleted
		&sql.NullString{},  // nodeType
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*PropertyType) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // resource_type_property_types
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PropertyType fields.
func (pt *PropertyType) assignValues(values ...interface{}) error {
	if m, n := len(values), len(propertytype.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	pt.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field type", values[0])
	} else if value.Valid {
		pt.Type = propertytype.Type(value.String)
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[1])
	} else if value.Valid {
		pt.Name = value.String
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field external_id", values[2])
	} else if value.Valid {
		pt.ExternalID = value.String
	}
	if value, ok := values[3].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field index", values[3])
	} else if value.Valid {
		pt.Index = int(value.Int64)
	}
	if value, ok := values[4].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field category", values[4])
	} else if value.Valid {
		pt.Category = value.String
	}
	if value, ok := values[5].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field int_val", values[5])
	} else if value.Valid {
		pt.IntVal = new(int)
		*pt.IntVal = int(value.Int64)
	}
	if value, ok := values[6].(*sql.NullBool); !ok {
		return fmt.Errorf("unexpected type %T for field bool_val", values[6])
	} else if value.Valid {
		pt.BoolVal = new(bool)
		*pt.BoolVal = value.Bool
	}
	if value, ok := values[7].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field float_val", values[7])
	} else if value.Valid {
		pt.FloatVal = new(float64)
		*pt.FloatVal = value.Float64
	}
	if value, ok := values[8].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field latitude_val", values[8])
	} else if value.Valid {
		pt.LatitudeVal = new(float64)
		*pt.LatitudeVal = value.Float64
	}
	if value, ok := values[9].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field longitude_val", values[9])
	} else if value.Valid {
		pt.LongitudeVal = new(float64)
		*pt.LongitudeVal = value.Float64
	}
	if value, ok := values[10].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field string_val", values[10])
	} else if value.Valid {
		pt.StringVal = new(string)
		*pt.StringVal = value.String
	}
	if value, ok := values[11].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field range_from_val", values[11])
	} else if value.Valid {
		pt.RangeFromVal = new(float64)
		*pt.RangeFromVal = value.Float64
	}
	if value, ok := values[12].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field range_to_val", values[12])
	} else if value.Valid {
		pt.RangeToVal = new(float64)
		*pt.RangeToVal = value.Float64
	}
	if value, ok := values[13].(*sql.NullBool); !ok {
		return fmt.Errorf("unexpected type %T for field is_instance_property", values[13])
	} else if value.Valid {
		pt.IsInstanceProperty = value.Bool
	}
	if value, ok := values[14].(*sql.NullBool); !ok {
		return fmt.Errorf("unexpected type %T for field editable", values[14])
	} else if value.Valid {
		pt.Editable = value.Bool
	}
	if value, ok := values[15].(*sql.NullBool); !ok {
		return fmt.Errorf("unexpected type %T for field mandatory", values[15])
	} else if value.Valid {
		pt.Mandatory = value.Bool
	}
	if value, ok := values[16].(*sql.NullBool); !ok {
		return fmt.Errorf("unexpected type %T for field deleted", values[16])
	} else if value.Valid {
		pt.Deleted = value.Bool
	}
	if value, ok := values[17].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field nodeType", values[17])
	} else if value.Valid {
		pt.NodeType = value.String
	}
	values = values[18:]
	if len(values) == len(propertytype.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field resource_type_property_types", value)
		} else if value.Valid {
			pt.resource_type_property_types = new(int)
			*pt.resource_type_property_types = int(value.Int64)
		}
	}
	return nil
}

// QueryProperties queries the properties edge of the PropertyType.
func (pt *PropertyType) QueryProperties() *PropertyQuery {
	return (&PropertyTypeClient{config: pt.config}).QueryProperties(pt)
}

// Update returns a builder for updating this PropertyType.
// Note that, you need to call PropertyType.Unwrap() before calling this method, if this PropertyType
// was returned from a transaction, and the transaction was committed or rolled back.
func (pt *PropertyType) Update() *PropertyTypeUpdateOne {
	return (&PropertyTypeClient{config: pt.config}).UpdateOne(pt)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (pt *PropertyType) Unwrap() *PropertyType {
	tx, ok := pt.config.driver.(*txDriver)
	if !ok {
		panic("ent: PropertyType is not a transactional entity")
	}
	pt.config.driver = tx.drv
	return pt
}

// String implements the fmt.Stringer.
func (pt *PropertyType) String() string {
	var builder strings.Builder
	builder.WriteString("PropertyType(")
	builder.WriteString(fmt.Sprintf("id=%v", pt.ID))
	builder.WriteString(", type=")
	builder.WriteString(fmt.Sprintf("%v", pt.Type))
	builder.WriteString(", name=")
	builder.WriteString(pt.Name)
	builder.WriteString(", external_id=")
	builder.WriteString(pt.ExternalID)
	builder.WriteString(", index=")
	builder.WriteString(fmt.Sprintf("%v", pt.Index))
	builder.WriteString(", category=")
	builder.WriteString(pt.Category)
	if v := pt.IntVal; v != nil {
		builder.WriteString(", int_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pt.BoolVal; v != nil {
		builder.WriteString(", bool_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pt.FloatVal; v != nil {
		builder.WriteString(", float_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pt.LatitudeVal; v != nil {
		builder.WriteString(", latitude_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pt.LongitudeVal; v != nil {
		builder.WriteString(", longitude_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pt.StringVal; v != nil {
		builder.WriteString(", string_val=")
		builder.WriteString(*v)
	}
	if v := pt.RangeFromVal; v != nil {
		builder.WriteString(", range_from_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pt.RangeToVal; v != nil {
		builder.WriteString(", range_to_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", is_instance_property=")
	builder.WriteString(fmt.Sprintf("%v", pt.IsInstanceProperty))
	builder.WriteString(", editable=")
	builder.WriteString(fmt.Sprintf("%v", pt.Editable))
	builder.WriteString(", mandatory=")
	builder.WriteString(fmt.Sprintf("%v", pt.Mandatory))
	builder.WriteString(", deleted=")
	builder.WriteString(fmt.Sprintf("%v", pt.Deleted))
	builder.WriteString(", nodeType=")
	builder.WriteString(pt.NodeType)
	builder.WriteByte(')')
	return builder.String()
}

// PropertyTypes is a parsable slice of PropertyType.
type PropertyTypes []*PropertyType

func (pt PropertyTypes) config(cfg config) {
	for _i := range pt {
		pt[_i].config = cfg
	}
}
