// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebook/ent/dialect/sql"
	"github.com/net-auto/resourceManager/ent/property"
	"github.com/net-auto/resourceManager/ent/propertytype"
)

// Property is the model entity for the Property schema.
type Property struct {
	config `gqlgen:"-" json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IntVal holds the value of the "int_val" field.
	IntVal *int `json:"intValue" gqlgen:"intValue"`
	// BoolVal holds the value of the "bool_val" field.
	BoolVal *bool `json:"booleanValue" gqlgen:"booleanValue"`
	// FloatVal holds the value of the "float_val" field.
	FloatVal *float64 `json:"floatValue" gqlgen:"floatValue"`
	// LatitudeVal holds the value of the "latitude_val" field.
	LatitudeVal *float64 `json:"latitudeValue" gqlgen:"latitudeValue"`
	// LongitudeVal holds the value of the "longitude_val" field.
	LongitudeVal *float64 `json:"longitudeValue" gqlgen:"longitudeValue"`
	// RangeFromVal holds the value of the "range_from_val" field.
	RangeFromVal *float64 `json:"rangeFromValue" gqlgen:"rangeFromValue"`
	// RangeToVal holds the value of the "range_to_val" field.
	RangeToVal *float64 `json:"rangeToValue" gqlgen:"rangeToValue"`
	// StringVal holds the value of the "string_val" field.
	StringVal *string `json:"stringValue" gqlgen:"stringValue"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PropertyQuery when eager-loading is set.
	Edges                      PropertyEdges `json:"edges"`
	pool_properties_properties *int
	property_type              *int
	resource_properties        *int
}

// PropertyEdges holds the relations/edges for other nodes in the graph.
type PropertyEdges struct {
	// Type holds the value of the type edge.
	Type *PropertyType `gqlgen:"propertyType"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TypeOrErr returns the Type value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PropertyEdges) TypeOrErr() (*PropertyType, error) {
	if e.loadedTypes[0] {
		if e.Type == nil {
			// The edge type was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: propertytype.Label}
		}
		return e.Type, nil
	}
	return nil, &NotLoadedError{edge: "type"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Property) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},   // id
		&sql.NullInt64{},   // int_val
		&sql.NullBool{},    // bool_val
		&sql.NullFloat64{}, // float_val
		&sql.NullFloat64{}, // latitude_val
		&sql.NullFloat64{}, // longitude_val
		&sql.NullFloat64{}, // range_from_val
		&sql.NullFloat64{}, // range_to_val
		&sql.NullString{},  // string_val
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Property) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // pool_properties_properties
		&sql.NullInt64{}, // property_type
		&sql.NullInt64{}, // resource_properties
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Property fields.
func (pr *Property) assignValues(values ...interface{}) error {
	if m, n := len(values), len(property.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	pr.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field int_val", values[0])
	} else if value.Valid {
		pr.IntVal = new(int)
		*pr.IntVal = int(value.Int64)
	}
	if value, ok := values[1].(*sql.NullBool); !ok {
		return fmt.Errorf("unexpected type %T for field bool_val", values[1])
	} else if value.Valid {
		pr.BoolVal = new(bool)
		*pr.BoolVal = value.Bool
	}
	if value, ok := values[2].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field float_val", values[2])
	} else if value.Valid {
		pr.FloatVal = new(float64)
		*pr.FloatVal = value.Float64
	}
	if value, ok := values[3].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field latitude_val", values[3])
	} else if value.Valid {
		pr.LatitudeVal = new(float64)
		*pr.LatitudeVal = value.Float64
	}
	if value, ok := values[4].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field longitude_val", values[4])
	} else if value.Valid {
		pr.LongitudeVal = new(float64)
		*pr.LongitudeVal = value.Float64
	}
	if value, ok := values[5].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field range_from_val", values[5])
	} else if value.Valid {
		pr.RangeFromVal = new(float64)
		*pr.RangeFromVal = value.Float64
	}
	if value, ok := values[6].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field range_to_val", values[6])
	} else if value.Valid {
		pr.RangeToVal = new(float64)
		*pr.RangeToVal = value.Float64
	}
	if value, ok := values[7].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field string_val", values[7])
	} else if value.Valid {
		pr.StringVal = new(string)
		*pr.StringVal = value.String
	}
	values = values[8:]
	if len(values) == len(property.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field pool_properties_properties", value)
		} else if value.Valid {
			pr.pool_properties_properties = new(int)
			*pr.pool_properties_properties = int(value.Int64)
		}
		if value, ok := values[1].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field property_type", value)
		} else if value.Valid {
			pr.property_type = new(int)
			*pr.property_type = int(value.Int64)
		}
		if value, ok := values[2].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field resource_properties", value)
		} else if value.Valid {
			pr.resource_properties = new(int)
			*pr.resource_properties = int(value.Int64)
		}
	}
	return nil
}

// QueryType queries the type edge of the Property.
func (pr *Property) QueryType() *PropertyTypeQuery {
	return (&PropertyClient{config: pr.config}).QueryType(pr)
}

// Update returns a builder for updating this Property.
// Note that, you need to call Property.Unwrap() before calling this method, if this Property
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Property) Update() *PropertyUpdateOne {
	return (&PropertyClient{config: pr.config}).UpdateOne(pr)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (pr *Property) Unwrap() *Property {
	tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Property is not a transactional entity")
	}
	pr.config.driver = tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Property) String() string {
	var builder strings.Builder
	builder.WriteString("Property(")
	builder.WriteString(fmt.Sprintf("id=%v", pr.ID))
	if v := pr.IntVal; v != nil {
		builder.WriteString(", int_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pr.BoolVal; v != nil {
		builder.WriteString(", bool_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pr.FloatVal; v != nil {
		builder.WriteString(", float_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pr.LatitudeVal; v != nil {
		builder.WriteString(", latitude_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pr.LongitudeVal; v != nil {
		builder.WriteString(", longitude_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pr.RangeFromVal; v != nil {
		builder.WriteString(", range_from_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pr.RangeToVal; v != nil {
		builder.WriteString(", range_to_val=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := pr.StringVal; v != nil {
		builder.WriteString(", string_val=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Properties is a parsable slice of Property.
type Properties []*Property

func (pr Properties) config(cfg config) {
	for _i := range pr {
		pr[_i].config = cfg
	}
}
