// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/net-auto/resourceManager/ent/label"
	"github.com/net-auto/resourceManager/ent/predicate"
	"github.com/net-auto/resourceManager/ent/resource"
	"github.com/net-auto/resourceManager/ent/resourcepool"
	"github.com/net-auto/resourceManager/ent/resourcetype"
)

// ResourcePoolUpdate is the builder for updating ResourcePool entities.
type ResourcePoolUpdate struct {
	config
	hooks      []Hook
	mutation   *ResourcePoolMutation
	predicates []predicate.ResourcePool
}

// Where adds a new predicate for the builder.
func (rpu *ResourcePoolUpdate) Where(ps ...predicate.ResourcePool) *ResourcePoolUpdate {
	rpu.predicates = append(rpu.predicates, ps...)
	return rpu
}

// SetName sets the name field.
func (rpu *ResourcePoolUpdate) SetName(s string) *ResourcePoolUpdate {
	rpu.mutation.SetName(s)
	return rpu
}

// SetPoolType sets the pool_type field.
func (rpu *ResourcePoolUpdate) SetPoolType(rt resourcepool.PoolType) *ResourcePoolUpdate {
	rpu.mutation.SetPoolType(rt)
	return rpu
}

// SetResourceTypeID sets the resource_type edge to ResourceType by id.
func (rpu *ResourcePoolUpdate) SetResourceTypeID(id int) *ResourcePoolUpdate {
	rpu.mutation.SetResourceTypeID(id)
	return rpu
}

// SetNillableResourceTypeID sets the resource_type edge to ResourceType by id if the given value is not nil.
func (rpu *ResourcePoolUpdate) SetNillableResourceTypeID(id *int) *ResourcePoolUpdate {
	if id != nil {
		rpu = rpu.SetResourceTypeID(*id)
	}
	return rpu
}

// SetResourceType sets the resource_type edge to ResourceType.
func (rpu *ResourcePoolUpdate) SetResourceType(r *ResourceType) *ResourcePoolUpdate {
	return rpu.SetResourceTypeID(r.ID)
}

// SetLabelsID sets the labels edge to Label by id.
func (rpu *ResourcePoolUpdate) SetLabelsID(id int) *ResourcePoolUpdate {
	rpu.mutation.SetLabelsID(id)
	return rpu
}

// SetNillableLabelsID sets the labels edge to Label by id if the given value is not nil.
func (rpu *ResourcePoolUpdate) SetNillableLabelsID(id *int) *ResourcePoolUpdate {
	if id != nil {
		rpu = rpu.SetLabelsID(*id)
	}
	return rpu
}

// SetLabels sets the labels edge to Label.
func (rpu *ResourcePoolUpdate) SetLabels(l *Label) *ResourcePoolUpdate {
	return rpu.SetLabelsID(l.ID)
}

// AddClaimIDs adds the claims edge to Resource by ids.
func (rpu *ResourcePoolUpdate) AddClaimIDs(ids ...int) *ResourcePoolUpdate {
	rpu.mutation.AddClaimIDs(ids...)
	return rpu
}

// AddClaims adds the claims edges to Resource.
func (rpu *ResourcePoolUpdate) AddClaims(r ...*Resource) *ResourcePoolUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rpu.AddClaimIDs(ids...)
}

// Mutation returns the ResourcePoolMutation object of the builder.
func (rpu *ResourcePoolUpdate) Mutation() *ResourcePoolMutation {
	return rpu.mutation
}

// ClearResourceType clears the resource_type edge to ResourceType.
func (rpu *ResourcePoolUpdate) ClearResourceType() *ResourcePoolUpdate {
	rpu.mutation.ClearResourceType()
	return rpu
}

// ClearLabels clears the labels edge to Label.
func (rpu *ResourcePoolUpdate) ClearLabels() *ResourcePoolUpdate {
	rpu.mutation.ClearLabels()
	return rpu
}

// RemoveClaimIDs removes the claims edge to Resource by ids.
func (rpu *ResourcePoolUpdate) RemoveClaimIDs(ids ...int) *ResourcePoolUpdate {
	rpu.mutation.RemoveClaimIDs(ids...)
	return rpu
}

// RemoveClaims removes claims edges to Resource.
func (rpu *ResourcePoolUpdate) RemoveClaims(r ...*Resource) *ResourcePoolUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rpu.RemoveClaimIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (rpu *ResourcePoolUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := rpu.mutation.Name(); ok {
		if err := resourcepool.NameValidator(v); err != nil {
			return 0, &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if v, ok := rpu.mutation.PoolType(); ok {
		if err := resourcepool.PoolTypeValidator(v); err != nil {
			return 0, &ValidationError{Name: "pool_type", err: fmt.Errorf("ent: validator failed for field \"pool_type\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(rpu.hooks) == 0 {
		affected, err = rpu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ResourcePoolMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rpu.mutation = mutation
			affected, err = rpu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rpu.hooks) - 1; i >= 0; i-- {
			mut = rpu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rpu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (rpu *ResourcePoolUpdate) SaveX(ctx context.Context) int {
	affected, err := rpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rpu *ResourcePoolUpdate) Exec(ctx context.Context) error {
	_, err := rpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpu *ResourcePoolUpdate) ExecX(ctx context.Context) {
	if err := rpu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rpu *ResourcePoolUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   resourcepool.Table,
			Columns: resourcepool.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: resourcepool.FieldID,
			},
		},
	}
	if ps := rpu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rpu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resourcepool.FieldName,
		})
	}
	if value, ok := rpu.mutation.PoolType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: resourcepool.FieldPoolType,
		})
	}
	if rpu.mutation.ResourceTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcepool.ResourceTypeTable,
			Columns: []string{resourcepool.ResourceTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpu.mutation.ResourceTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcepool.ResourceTypeTable,
			Columns: []string{resourcepool.ResourceTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if rpu.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcepool.LabelsTable,
			Columns: []string{resourcepool.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: label.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpu.mutation.LabelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcepool.LabelsTable,
			Columns: []string{resourcepool.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: label.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := rpu.mutation.RemovedClaimsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcepool.ClaimsTable,
			Columns: []string{resourcepool.ClaimsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resource.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpu.mutation.ClaimsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcepool.ClaimsTable,
			Columns: []string{resourcepool.ClaimsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resource.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcepool.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ResourcePoolUpdateOne is the builder for updating a single ResourcePool entity.
type ResourcePoolUpdateOne struct {
	config
	hooks    []Hook
	mutation *ResourcePoolMutation
}

// SetName sets the name field.
func (rpuo *ResourcePoolUpdateOne) SetName(s string) *ResourcePoolUpdateOne {
	rpuo.mutation.SetName(s)
	return rpuo
}

// SetPoolType sets the pool_type field.
func (rpuo *ResourcePoolUpdateOne) SetPoolType(rt resourcepool.PoolType) *ResourcePoolUpdateOne {
	rpuo.mutation.SetPoolType(rt)
	return rpuo
}

// SetResourceTypeID sets the resource_type edge to ResourceType by id.
func (rpuo *ResourcePoolUpdateOne) SetResourceTypeID(id int) *ResourcePoolUpdateOne {
	rpuo.mutation.SetResourceTypeID(id)
	return rpuo
}

// SetNillableResourceTypeID sets the resource_type edge to ResourceType by id if the given value is not nil.
func (rpuo *ResourcePoolUpdateOne) SetNillableResourceTypeID(id *int) *ResourcePoolUpdateOne {
	if id != nil {
		rpuo = rpuo.SetResourceTypeID(*id)
	}
	return rpuo
}

// SetResourceType sets the resource_type edge to ResourceType.
func (rpuo *ResourcePoolUpdateOne) SetResourceType(r *ResourceType) *ResourcePoolUpdateOne {
	return rpuo.SetResourceTypeID(r.ID)
}

// SetLabelsID sets the labels edge to Label by id.
func (rpuo *ResourcePoolUpdateOne) SetLabelsID(id int) *ResourcePoolUpdateOne {
	rpuo.mutation.SetLabelsID(id)
	return rpuo
}

// SetNillableLabelsID sets the labels edge to Label by id if the given value is not nil.
func (rpuo *ResourcePoolUpdateOne) SetNillableLabelsID(id *int) *ResourcePoolUpdateOne {
	if id != nil {
		rpuo = rpuo.SetLabelsID(*id)
	}
	return rpuo
}

// SetLabels sets the labels edge to Label.
func (rpuo *ResourcePoolUpdateOne) SetLabels(l *Label) *ResourcePoolUpdateOne {
	return rpuo.SetLabelsID(l.ID)
}

// AddClaimIDs adds the claims edge to Resource by ids.
func (rpuo *ResourcePoolUpdateOne) AddClaimIDs(ids ...int) *ResourcePoolUpdateOne {
	rpuo.mutation.AddClaimIDs(ids...)
	return rpuo
}

// AddClaims adds the claims edges to Resource.
func (rpuo *ResourcePoolUpdateOne) AddClaims(r ...*Resource) *ResourcePoolUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rpuo.AddClaimIDs(ids...)
}

// Mutation returns the ResourcePoolMutation object of the builder.
func (rpuo *ResourcePoolUpdateOne) Mutation() *ResourcePoolMutation {
	return rpuo.mutation
}

// ClearResourceType clears the resource_type edge to ResourceType.
func (rpuo *ResourcePoolUpdateOne) ClearResourceType() *ResourcePoolUpdateOne {
	rpuo.mutation.ClearResourceType()
	return rpuo
}

// ClearLabels clears the labels edge to Label.
func (rpuo *ResourcePoolUpdateOne) ClearLabels() *ResourcePoolUpdateOne {
	rpuo.mutation.ClearLabels()
	return rpuo
}

// RemoveClaimIDs removes the claims edge to Resource by ids.
func (rpuo *ResourcePoolUpdateOne) RemoveClaimIDs(ids ...int) *ResourcePoolUpdateOne {
	rpuo.mutation.RemoveClaimIDs(ids...)
	return rpuo
}

// RemoveClaims removes claims edges to Resource.
func (rpuo *ResourcePoolUpdateOne) RemoveClaims(r ...*Resource) *ResourcePoolUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rpuo.RemoveClaimIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (rpuo *ResourcePoolUpdateOne) Save(ctx context.Context) (*ResourcePool, error) {
	if v, ok := rpuo.mutation.Name(); ok {
		if err := resourcepool.NameValidator(v); err != nil {
			return nil, &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if v, ok := rpuo.mutation.PoolType(); ok {
		if err := resourcepool.PoolTypeValidator(v); err != nil {
			return nil, &ValidationError{Name: "pool_type", err: fmt.Errorf("ent: validator failed for field \"pool_type\": %w", err)}
		}
	}

	var (
		err  error
		node *ResourcePool
	)
	if len(rpuo.hooks) == 0 {
		node, err = rpuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ResourcePoolMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rpuo.mutation = mutation
			node, err = rpuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rpuo.hooks) - 1; i >= 0; i-- {
			mut = rpuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rpuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (rpuo *ResourcePoolUpdateOne) SaveX(ctx context.Context) *ResourcePool {
	rp, err := rpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return rp
}

// Exec executes the query on the entity.
func (rpuo *ResourcePoolUpdateOne) Exec(ctx context.Context) error {
	_, err := rpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpuo *ResourcePoolUpdateOne) ExecX(ctx context.Context) {
	if err := rpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rpuo *ResourcePoolUpdateOne) sqlSave(ctx context.Context) (rp *ResourcePool, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   resourcepool.Table,
			Columns: resourcepool.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: resourcepool.FieldID,
			},
		},
	}
	id, ok := rpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing ResourcePool.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := rpuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resourcepool.FieldName,
		})
	}
	if value, ok := rpuo.mutation.PoolType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: resourcepool.FieldPoolType,
		})
	}
	if rpuo.mutation.ResourceTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcepool.ResourceTypeTable,
			Columns: []string{resourcepool.ResourceTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpuo.mutation.ResourceTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcepool.ResourceTypeTable,
			Columns: []string{resourcepool.ResourceTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if rpuo.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcepool.LabelsTable,
			Columns: []string{resourcepool.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: label.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpuo.mutation.LabelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcepool.LabelsTable,
			Columns: []string{resourcepool.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: label.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := rpuo.mutation.RemovedClaimsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcepool.ClaimsTable,
			Columns: []string{resourcepool.ClaimsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resource.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpuo.mutation.ClaimsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcepool.ClaimsTable,
			Columns: []string{resourcepool.ClaimsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resource.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	rp = &ResourcePool{config: rpuo.config}
	_spec.Assign = rp.assignValues
	_spec.ScanValues = rp.scanValues()
	if err = sqlgraph.UpdateNode(ctx, rpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcepool.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return rp, nil
}
