// Code generated by entc, DO NOT EDIT.

package privacy

import (
	"context"
	"fmt"

	"github.com/net-auto/resourceManager/ent"

	"github.com/facebook/ent/privacy"
)

var (
	// Allow may be returned by rules to indicate that the policy
	// evaluation should terminate with an allow decision.
	Allow = privacy.Allow

	// Deny may be returned by rules to indicate that the policy
	// evaluation should terminate with an deny decision.
	Deny = privacy.Deny

	// Skip may be returned by rules to indicate that the policy
	// evaluation should continue to the next rule.
	Skip = privacy.Skip
)

// Allowf returns an formatted wrapped Allow decision.
func Allowf(format string, a ...interface{}) error {
	return fmt.Errorf(format+": %w", append(a, Allow)...)
}

// Denyf returns an formatted wrapped Deny decision.
func Denyf(format string, a ...interface{}) error {
	return fmt.Errorf(format+": %w", append(a, Deny)...)
}

// Skipf returns an formatted wrapped Skip decision.
func Skipf(format string, a ...interface{}) error {
	return fmt.Errorf(format+": %w", append(a, Skip)...)
}

// DecisionContext creates a new context from the given parent context with
// a policy decision attach to it.
func DecisionContext(parent context.Context, decision error) context.Context {
	return privacy.DecisionContext(parent, decision)
}

// DecisionFromContext retrieves the policy decision from the context.
func DecisionFromContext(ctx context.Context) (error, bool) {
	return privacy.DecisionFromContext(ctx)
}

type (
	// QueryRule defines the interface deciding whether a
	// query is allowed and optionally modify it.
	QueryRule = privacy.QueryRule
	// QueryPolicy combines multiple query rules into a single policy.
	QueryPolicy = privacy.QueryPolicy
)

// QueryRuleFunc type is an adapter to allow the use of
// ordinary functions as query rules.
type QueryRuleFunc func(context.Context, ent.Query) error

// Eval returns f(ctx, q).
func (f QueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	return f(ctx, q)
}

type (
	// MutationRule defines the interface deciding whether a
	// mutation is allowed and optionally modify it.
	MutationRule = privacy.MutationRule
	// MutationPolicy combines multiple mutation rules into a single policy.
	MutationPolicy = privacy.MutationPolicy
)

// MutationRuleFunc type is an adapter to allow the use of
// ordinary functions as mutation rules.
type MutationRuleFunc func(context.Context, ent.Mutation) error

// EvalMutation returns f(ctx, m).
func (f MutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	return f(ctx, m)
}

// Policy groups query and mutation policies.
type Policy struct {
	Query    QueryPolicy
	Mutation MutationPolicy
}

// EvalQuery forwards evaluation to query policy.
func (policy Policy) EvalQuery(ctx context.Context, q ent.Query) error {
	return policy.Query.EvalQuery(ctx, q)
}

// EvalMutation forwards evaluation to mutation policy.
func (policy Policy) EvalMutation(ctx context.Context, m ent.Mutation) error {
	return policy.Mutation.EvalMutation(ctx, m)
}

// QueryMutationRule is the interface that groups query and mutation rules.
type QueryMutationRule interface {
	QueryRule
	MutationRule
}

// AlwaysAllowRule returns a rule that returns an allow decision.
func AlwaysAllowRule() QueryMutationRule {
	return fixedDecision{Allow}
}

// AlwaysDenyRule returns a rule that returns a deny decision.
func AlwaysDenyRule() QueryMutationRule {
	return fixedDecision{Deny}
}

type fixedDecision struct {
	decision error
}

func (f fixedDecision) EvalQuery(context.Context, ent.Query) error {
	return f.decision
}

func (f fixedDecision) EvalMutation(context.Context, ent.Mutation) error {
	return f.decision
}

type contextDecision struct {
	eval func(context.Context) error
}

// ContextQueryMutationRule creates a query/mutation rule from a context eval func.
func ContextQueryMutationRule(eval func(context.Context) error) QueryMutationRule {
	return contextDecision{eval}
}

func (c contextDecision) EvalQuery(ctx context.Context, _ ent.Query) error {
	return c.eval(ctx)
}

func (c contextDecision) EvalMutation(ctx context.Context, _ ent.Mutation) error {
	return c.eval(ctx)
}

// OnMutationOperation evaluates the given rule only on a given mutation operation.
func OnMutationOperation(rule MutationRule, op ent.Op) MutationRule {
	return MutationRuleFunc(func(ctx context.Context, m ent.Mutation) error {
		if m.Op().Is(op) {
			return rule.EvalMutation(ctx, m)
		}
		return Skip
	})
}

// DenyMutationOperationRule returns a rule denying specified mutation operation.
func DenyMutationOperationRule(op ent.Op) MutationRule {
	rule := MutationRuleFunc(func(_ context.Context, m ent.Mutation) error {
		return Denyf("ent/privacy: operation %s is not allowed", m.Op())
	})
	return OnMutationOperation(rule, op)
}

// The AllocationStrategyQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type AllocationStrategyQueryRuleFunc func(context.Context, *ent.AllocationStrategyQuery) error

// EvalQuery return f(ctx, q).
func (f AllocationStrategyQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AllocationStrategyQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.AllocationStrategyQuery", q)
}

// The AllocationStrategyMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type AllocationStrategyMutationRuleFunc func(context.Context, *ent.AllocationStrategyMutation) error

// EvalMutation calls f(ctx, m).
func (f AllocationStrategyMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.AllocationStrategyMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.AllocationStrategyMutation", m)
}

// The PoolPropertiesQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type PoolPropertiesQueryRuleFunc func(context.Context, *ent.PoolPropertiesQuery) error

// EvalQuery return f(ctx, q).
func (f PoolPropertiesQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PoolPropertiesQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.PoolPropertiesQuery", q)
}

// The PoolPropertiesMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type PoolPropertiesMutationRuleFunc func(context.Context, *ent.PoolPropertiesMutation) error

// EvalMutation calls f(ctx, m).
func (f PoolPropertiesMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.PoolPropertiesMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.PoolPropertiesMutation", m)
}

// The PropertyQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type PropertyQueryRuleFunc func(context.Context, *ent.PropertyQuery) error

// EvalQuery return f(ctx, q).
func (f PropertyQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PropertyQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.PropertyQuery", q)
}

// The PropertyMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type PropertyMutationRuleFunc func(context.Context, *ent.PropertyMutation) error

// EvalMutation calls f(ctx, m).
func (f PropertyMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.PropertyMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.PropertyMutation", m)
}

// The PropertyTypeQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type PropertyTypeQueryRuleFunc func(context.Context, *ent.PropertyTypeQuery) error

// EvalQuery return f(ctx, q).
func (f PropertyTypeQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PropertyTypeQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.PropertyTypeQuery", q)
}

// The PropertyTypeMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type PropertyTypeMutationRuleFunc func(context.Context, *ent.PropertyTypeMutation) error

// EvalMutation calls f(ctx, m).
func (f PropertyTypeMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.PropertyTypeMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.PropertyTypeMutation", m)
}

// The ResourceQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type ResourceQueryRuleFunc func(context.Context, *ent.ResourceQuery) error

// EvalQuery return f(ctx, q).
func (f ResourceQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ResourceQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.ResourceQuery", q)
}

// The ResourceMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type ResourceMutationRuleFunc func(context.Context, *ent.ResourceMutation) error

// EvalMutation calls f(ctx, m).
func (f ResourceMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.ResourceMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.ResourceMutation", m)
}

// The ResourcePoolQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type ResourcePoolQueryRuleFunc func(context.Context, *ent.ResourcePoolQuery) error

// EvalQuery return f(ctx, q).
func (f ResourcePoolQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ResourcePoolQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.ResourcePoolQuery", q)
}

// The ResourcePoolMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type ResourcePoolMutationRuleFunc func(context.Context, *ent.ResourcePoolMutation) error

// EvalMutation calls f(ctx, m).
func (f ResourcePoolMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.ResourcePoolMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.ResourcePoolMutation", m)
}

// The ResourceTypeQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type ResourceTypeQueryRuleFunc func(context.Context, *ent.ResourceTypeQuery) error

// EvalQuery return f(ctx, q).
func (f ResourceTypeQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ResourceTypeQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.ResourceTypeQuery", q)
}

// The ResourceTypeMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type ResourceTypeMutationRuleFunc func(context.Context, *ent.ResourceTypeMutation) error

// EvalMutation calls f(ctx, m).
func (f ResourceTypeMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.ResourceTypeMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.ResourceTypeMutation", m)
}

// The TagQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type TagQueryRuleFunc func(context.Context, *ent.TagQuery) error

// EvalQuery return f(ctx, q).
func (f TagQueryRuleFunc) EvalQuery(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TagQuery); ok {
		return f(ctx, q)
	}
	return Denyf("ent/privacy: unexpected query type %T, expect *ent.TagQuery", q)
}

// The TagMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type TagMutationRuleFunc func(context.Context, *ent.TagMutation) error

// EvalMutation calls f(ctx, m).
func (f TagMutationRuleFunc) EvalMutation(ctx context.Context, m ent.Mutation) error {
	if m, ok := m.(*ent.TagMutation); ok {
		return f(ctx, m)
	}
	return Denyf("ent/privacy: unexpected mutation type %T, expect *ent.TagMutation", m)
}
