// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// AllocationStrategy is the predicate function for allocationstrategy builders.
type AllocationStrategy func(*sql.Selector)

// PoolProperties is the predicate function for poolproperties builders.
type PoolProperties func(*sql.Selector)

// Property is the predicate function for property builders.
type Property func(*sql.Selector)

// PropertyType is the predicate function for propertytype builders.
type PropertyType func(*sql.Selector)

// Resource is the predicate function for resource builders.
type Resource func(*sql.Selector)

// ResourcePool is the predicate function for resourcepool builders.
type ResourcePool func(*sql.Selector)

// ResourceType is the predicate function for resourcetype builders.
type ResourceType func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
